# Generated by Django 5.2.5 on 2025-10-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_tx_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
