# Generated by Django 5.2.5 on 2025-08-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_courierapplication_vehicle_alter_courier_user'),
        ('shipments', '0003_alter_shipment_destination_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='shipments.shipment'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'ACCEPTED'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=20),
        ),
    ]
