# Generated by Django 5.2.5 on 2025-08-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliveryassignment_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=20),
        ),
    ]
