# Generated by Django 5.2.5 on 2025-09-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_deliveryassignment_status'),
        ('shipments', '0004_shipment_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryassignment', to='shipments.shipment'),
        ),
    ]
