# Generated by Django 5.2.5 on 2025-08-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('courier', 'Courier'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
