# Generated by Django 5.2.5 on 2025-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_rename_shipments_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='destination_address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin_address',
            field=models.TextField(max_length=255),
        ),
    ]
