# Generated by Django 5.2.5 on 2025-09-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_shipment_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
